# It's numpy showdown

### Importing

In [1]:
import numpy as np

### Basics

In [2]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(x[2:],'||',x[:4],'||',x[2:4])

[2 3 4 5 6 7 8 9] || [0 1 2 3] || [2 3]


In [4]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Playing with boolean and indexes

In [5]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [6]:
x[x>3]

array([4, 5, 6, 7, 8, 9])

### Copies

In [7]:
#Obsereve how x and y operate in same memory
x = np.arange(12)
y = x[:5]

print(x,y)
y[0] = 10
print(x,y)

[ 0  1  2  3  4  5  6  7  8  9 10 11] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9 10 11] [10  1  2  3  4]


In [8]:
#Now observe the use of .copy
x = np.arange(12)
y = x[:5].copy()

print(x,y)
y[0] = 10
print('#use of . copy()')
print(x,y)

[ 0  1  2  3  4  5  6  7  8  9 10 11] [0 1 2 3 4]
#use of . copy()
[ 0  1  2  3  4  5  6  7  8  9 10 11] [10  1  2  3  4]


### Random numbers

In [9]:
#Normal distribution
np.random.normal(-1,1,10)

array([-1.6249099 , -0.4085218 ,  0.43732459, -0.50813709, -2.04139737,
       -0.93966258, -0.63596817,  0.78618079, -1.14048536,  0.7090636 ])

In [10]:
a=np.random.randint(1,50,10)#Range==1 to 5, size=10
a

array([22,  8, 39, 41, 44,  4, 23, 40, 22,  6])

In [11]:
np.sort(a)

array([ 4,  6,  8, 22, 22, 23, 39, 40, 41, 44])

### Choice

In [12]:
##Generates a random sample from a given 1-D array
#p=probablity (optional)
#size=output_size
np.random.choice([2,4,5,6,7],size=(2,2,2),p=[0.1,0.2,0.3,0.2,0.2])

array([[[5, 5],
        [6, 6]],

       [[4, 6],
        [7, 5]]])

In [13]:
names=['Eminem','MJ','Queens','Ali Zafar']
np.random.choice(names, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['Eminem', 'Ali Zafar', 'Eminem', 'MJ', 'Queens'], dtype='<U9')

### Multidimensional arrays

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[2]

array([35, 40, 45])

In [73]:
arr_2d[2][2]

45

In [76]:
arr_2d[1:,2:]

array([[30],
       [45]])

In [78]:
inverse = np.linalg.inv(arr_2d)
inverse

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [79]:
A = np.mat('0 1 2; 1 0 3; 4 -3 8')
A

matrix([[ 0,  1,  2],
        [ 1,  0,  3],
        [ 4, -3,  8]])

In [80]:
b = np.array([0, 8, -9])
b

array([ 0,  8, -9])

In [81]:
# Ax = b
x = np.linalg.solve(A, b)
x

array([ 69.5,  41. , -20.5])

### Creating numpy arrays through different ways

In [14]:
list_1=[1,2,3,4,5]
np_arr=np.array(list_1)
np_arr

array([1, 2, 3, 4, 5])

In [15]:
matrix=[[1,2,3,4],[5,6,7,8]]
np_mat=np.array(matrix)
np_mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.arange(1,13,3) # start, stop(exclusive), step size

array([ 1,  4,  7, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.random.rand(2,4)

array([[0.59352934, 0.41347218, 0.57688573, 0.91172325],
       [0.46052568, 0.10313776, 0.40369742, 0.99588893]])

In [23]:
np.random.randn(2,4)

array([[-0.10241463,  0.21147067,  0.45384489,  1.91474848],
       [-1.86047704,  1.16898113,  0.03562642, -1.00454026]])

In [24]:
np.random.randint(1,100)  # low is inclusive, high is exclusive

69

In [25]:
np.random.randint(1,100,10)

array([29, 74, 33, 59, 98, 61,  4, 23, 95, 24])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
a=np.random.randint(1,100,10)
a

array([75, 20, 25, 81, 34, 17, 59, 48, 30, 86])

### Basic methods & attributes

In [28]:
a=a.reshape(2,5)
a

array([[75, 20, 25, 81, 34],
       [17, 59, 48, 30, 86]])

In [29]:
a.shape

(2, 5)

In [30]:
a.min()

17

In [31]:
a.max()

86

In [32]:
a.argmin()

5

In [33]:
a.argmax()

9

### Operations on numpy arrays

In [34]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
100*a-a

array([ 99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [38]:
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [39]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
b=np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a/b

/home/sachin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
       1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111])

In [42]:
#a/2*np.arange(1,21) #Check the dimensionality error

In [43]:
a.mean()

5.5

In [44]:
a**a

array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489, 10000000000])

In [45]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [46]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [47]:
np.max(a)

10

In [48]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [49]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

### Other operations

In [50]:
#Inversing a numpy array
a=np.arange(11)
a=a[::-1]
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [51]:
#Find indices of non-zero elements
nz=np.nonzero([0,2,3,0,0,1,2,9])
nz

(array([1, 2, 5, 6, 7]),)

In [53]:
#Padding with zeros
Z = np.zeros((10,10))
Z[1:-1,1:-1] = 1
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [54]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [55]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [56]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [57]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [60]:
#Checking if there are null columns
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [61]:
Z

array([[1, 1, 2, 2, 2, 1, 2, 1, 1, 1],
       [0, 1, 2, 0, 2, 2, 2, 0, 0, 0],
       [0, 1, 1, 2, 1, 0, 2, 0, 2, 1]])

In [63]:
a=np.random.uniform(-1,1,(4,4))
print(a)
print('-------------------------------------')
diag=np.diag(a)
print(diag)

[[-0.90745059 -0.17063948  0.74017853  0.86546796]
 [-0.85113776 -0.62583279 -0.21189467  0.036944  ]
 [-0.36667091  0.56159248  0.57327165  0.0455942 ]
 [ 0.93263192  0.20030726  0.67945159 -0.81835958]]
-------------------------------------
[-0.90745059 -0.62583279  0.57327165 -0.81835958]


In [67]:
#Swapping two rows
A = np.arange(25).reshape(5,5)
A[[2,3]] = A[[3,2]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [20 21 22 23 24]]
